name: .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test
      - name: Publish
        run: |
          dotnet publish Vocab3000 -c Release -o Vocab3000
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Vocab3000
          path: ${{ github.workspace }}/Vocab3000/bin/Release/netcoreapp3.1
